### ISSUE TITLE
Incompatibility with Tweak My Client

### ISSUE THREAD

**Issue by Anoaxx** [FalsehoodMC/Fabrication#444]
[latest.log](https://github.com/unascribed/Fabrication/files/8356706/latest.log)

and crashlog: 
`java.lang.ClassCastException: class net.minecraft.class_310 cannot be cast to class top.hendrixshen.TweakMyClient.interfaces.IMinecraft (net.minecraft.class_310 and top.hendrixshen.TweakMyClient.interfaces.IMinecraft are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @584f54e6)
	at net.minecraft.client.main.Main.handler$bkh000$finishInitializationRenderSystem(Main.java:522)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)`

Even if its not on Fabrication without it TMK works on 1.18.2

**Comment by exaskye** [comment]
exp3 has been released, which may fix this issue: https://github.com/unascribed/Fabrication/releases/download/v2.3.0/fabrication-1.18.2-2.3.1-exp3.jar

**Comment by Anoaxx** [comment]
its working
