### ISSUE TITLE
Update for 1.19.1

### ISSUE THREAD

**Issue by litoj** [FalsehoodMC/Fabrication#521]
```
[11:01:76] [Render thread/ERROR]: Mixin apply for mod fabrication failed fabrication.mixins.json:b_utility.chat_markdown.MixinServerPlayNetworkHandler from mod fabrication -> net.minecraft.class_3244: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded RuntimeException whilst transforming the mixin class: [INJECT Applicator Phase -> fabrication.mixins.json:b_utility.chat_markdown.MixinServerPlayNetworkHandler from mod fabrication -> Apply Injections -> PostInject -> fabrication.mixins.json:b_utility.chat_markdown.MixinServerPlayNetworkHandler from mod fabrication->@FabModifyArg::consume(Ljava/lang/String;)Ljava/lang/String;]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded RuntimeException whilst transforming the mixin class: [INJECT Applicator Phase -> fabrication.mixins.json:b_utility.chat_markdown.MixinServerPlayNetworkHandler from mod fabrication -> Apply Injections -> PostInject -> fabrication.mixins.json:b_utility.chat_markdown.MixinServerPlayNetworkHandler from mod fabrication->@FabModifyArg::consume(Ljava/lang/String;)Ljava/lang/String;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1394)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.lambda$static$1(S2CPlayChannelEvents.java:36)
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:57)
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:53)
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:44)
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:63)
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.<clinit>(S2CPlayChannelEvents.java:36)
	at net.fabricmc.fabric.impl.networking.OldNetworkingHooks.onInitialize(OldNetworkingHooks.java:27)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method consume(Ljava/lang/String;)Ljava/lang/String; in fabrication.mixins.json:b_utility.chat_markdown.MixinServerPlayNetworkHandler from mod fabrication failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabrication-refmap.json
	at com.unascribed.fabrication.support.injection.FabMixinInjector.handleErrorProactively(FabMixinInjector.java:71)
	at com.unascribed.fabrication.support.injection.FailsoftModifyArgInjectionInfo.postInject(FailsoftModifyArgInjectionInfo.java:25)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	... 29 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method consume(Ljava/lang/String;)Ljava/lang/String; in fabrication.mixins.json:b_utility.chat_markdown.MixinServerPlayNetworkHandler from mod fabrication failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabrication-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at com.unascribed.fabrication.support.injection.FailsoftModifyArgInjectionInfo.postInject(FailsoftModifyArgInjectionInfo.java:23)
	... 30 more
```

**Comment by exaskye** [comment]
Duplicate of #515
