### ISSUE TITLE
Ping privacy crashes on 1.19.4

### ISSUE THREAD

**Issue by ghost** [FalsehoodMC/Fabrication#595]
<details>
<summary>crash log</summary>

[14:58:44] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.18
[14:58:44] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[14:58:44] [main/INFO]: Loading 7 mods:
	- fabrication 3.2.4+1.19.4
	   \-- lib39-deferral 1.5.0-pre2.2+1.19.3
	- fabricloader 0.14.18
	- java 17
	- memoryleakfix 1.0.0
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	- minecraft 1.19.4
[14:58:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/stacy/AppData/Roaming/gdlauncher_next/datastore/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:58:44] [main/INFO]: Compatibility level set to JAVA_17
[14:58:45] [main/INFO]: [Fabrication] Reloading configs...
[14:58:45] [main/INFO]: [Fabrication] Loading of features.ini done in 27.64 ms with 0 warnings
[14:58:45] [main/WARN]: Reference map 'lib39-deferral-refmap.json' for lib39-deferral.mixins.json could not be read. If this is a development environment you can ignore this message
[14:58:45] [main/INFO]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[14:58:45] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[14:58:53] [Render thread/INFO]: [Fabrication] Loading of fscript.ini done in 1.941 ms with 0 warnings
[14:58:53] [Render thread/INFO]: [Fabrication] Loading of gear_components.ini done in 18.65 ms with 0 warnings
[14:58:53] [Render thread/INFO]: [Fabrication] Loading of block_logo.png done in 13.83 ms with 0 warnings
[14:58:53] [Render thread/INFO]: [Fabrication] Loading of block_logo.ini done in 19.58 ms with 0 warnings
[14:58:53] [Render thread/INFO]: [Fabrication] Loading of dimensional_tools.ini done in 8.204 ms with 0 warnings
[14:58:53] [Render thread/INFO]: [Fabrication] Loading of yeet_recipes.ini done in 1.063 ms with 0 warnings
[14:58:53] [Render thread/INFO]: [Fabrication] Loading of taggable_players.ini done in 7.915 ms with 0 warnings
[14:58:53] [Render thread/INFO]: [Fabrication] Loading of classic_block_drops.ini done in 1.912 ms with 0 warnings
[14:58:53] [Render thread/INFO]: [Fabrication] Loading of item_despawn.ini done in 4.360 ms with 0 warnings
[14:58:53] [Render thread/INFO]: [Fabrication] Injecting mutable resource pack provider set, as no-one else has yet.
[14:58:55] [Render thread/INFO]: [MemoryLeakFix] Attempting to ForceLoad All Mixins and clear cache
[14:58:55] [Render thread/ERROR]: Mixin apply for mod fabrication failed fabrication.mixins.json:b_utility.ping_privacy.MixinServerQueryNetworkHandler from mod fabrication -> net.minecraft.class_3251: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field server was not located in the target class net.minecraft.class_3251. Using refmap fabrication-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field server was not located in the target class net.minecraft.class_3251. Using refmap fabrication-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) [fabric-loader-0.14.18.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) [?:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96) [fabric-loader-0.14.18.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.audit(MixinProcessor.java:254) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.audit(MixinTransformer.java:171) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.MixinEnvironment.audit(MixinEnvironment.java:1425) [sponge-mixin-0.12.4+mixin.0.8.5.jar:0.12.4+mixin.0.8.5]
	at ca.fxco.memoryleakfix.fabric.MemoryLeakFixFabric.internalForceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFixFabric.java:40) [memoryleakfix-fabric-1.17+-1.0.0.jar:?]
	at ca.fxco.memoryleakfix.fabric.MemoryLeakFixFabric.forceLoadAllMixinsAndClearSpongePoweredCache(MemoryLeakFixFabric.java:32) [memoryleakfix-fabric-1.17+-1.0.0.jar:?]
	at net.minecraft.class_310.handler$bcb000$memoryleakfix$memoryLeakFix$loadAllMixinsClientSide(class_310.java:4500) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.18.jar:?]

</details>

**Comment by SFort** [comment]
set `ping_privacy` to banned for now
turns out i didn't port this feature at the time
